site_name: Genomics Workflows on AWS
nav:
  - Overview: index.md
  - Disclaimer: disclaimer.md
  - Quick Start: quick-start.md
  - Core Environment:
    - Introduction: core-env/introduction.md
    - Data Storage: core-env/create-s3-bucket.md
    - Permissions: core-env/create-iam-roles.md
    - Compute Resources: core-env/create-custom-compute-resources.md
    - AWS Batch: core-env/setup-aws-batch.md
    - Customized Deployment: core-env/custom-deploy.md
    - Building a Custom Distribution: core-env/build-custom-distribution.md
  # - Containerized Tooling:
  #   - Introduction: containers/container-introduction.md
  #   - Examples: containers/container-examples.md
  - Workflow Orchestration:
    - Introduction: orchestration/orchestration-intro.md
    - AWS Step Functions:
      - Overview: orchestration/step-functions/step-functions-overview.md
      # - Examples: orchestration/step-functions/step-functions-examples.md
    - Cromwell:
      - Overview: orchestration/cromwell/cromwell-overview.md
      - Examples: orchestration/cromwell/cromwell-examples.md
      - Trouble Shooting: orchestration/cromwell/cromwell-trouble-shooting.md
    - Nextflow: 
      - Overview: orchestration/nextflow/nextflow-overview.md
      # - Examples: orchestration/nextflow/nextflow-examples.md
      - Trouble Shooting: orchestration/nextflow/nextflow-trouble-shooting.md
    - Cost Effective Workflows: orchestration/cost-effective-workflows/cost-effective-workflows.md

extra_css: [extra.css]
theme: 
  name: material
  logo: 'images/AWS_logo_RGB_REV.svg'
  palette:
    primary: blue grey
    accent: deep orange
markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png

repo_url: &repo_url https://github.com/aws-samples/aws-genomics-workflows/
repo_name: Contribute
copyright: 2019 Amazon Web Services

plugins:
- search
- macros

extra:
  repo_url: *repo_url
  artifacts:
    s3: 
      bucket: aws-genomics-workflows
  site:
    s3:
      bucket: docs.opendata.aws
      prefix: genomics-workflows

use_directory_urls: false